theme: jekyll-theme-minimal
title: "Muon Spectroscopy and Galaxy Computational Project"
description: "A hub for tutorials, resources, and computational methods."
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
navbar:
  - name: "Home"
    link: /
  - name: "Muon Project"
    link: /muon/
  - name: "Galaxy Project"
    link: /galaxy/
  
